const mongoose = require('mongoose');

// mongoosejs.com/docs/schematypes.html
const UploadMercadopagoReportesCobrosSchema = mongoose.Schema({
    date_created:{
        type:Date
    },
    date_approved:{
        type:Date
    },
    date_released:{
        type:Date
    },
    counterpart_name:{
        type:String,
        trim:true
    },
    counterpart_nickname:{
        type:String,
        trim:true
    },
    counterpart_email:{
        type:String,
        trim:true
    },
    counterpart_phone_number:{
        type:String,
        trim:true
    },
    buyer_document:{
        type:Number
    },
    item_id:{
        type:String,
        trim:true
    },
    reason:{
        type:String,
        trim:true
    },
    external_reference:{
        type:String,
        trim:true
    },
    seller_custom_field:{
        type:String,
        trim:true
    },
    operation_id:{
        type:Number,
        required:true,
        unique:true
    },
    status:{
        type:String,
        required:true,
        trim:true
    },
    status_detail:{
        type:String,
        required:true,
        trim:true
    },
    operation_type:{
        type:String,
        required:true,
        trim:true
    },
    transaction_amount:{
        type:Number
    },
    mercadopago_fee:{
        type:Number
    },
    marketplace_fee:{
        type:Number
    },
    shipping_cost:{
        type:Number
    },
    coupon_fee:{
        type:Number
    },
    net_received_amount:{
        type:Number
    },
    installments:{
        type:Number
    },
    payment_type:{
        type:String,
        required:true,
        trim:true
    },
    amount_refunded:{
        type:Number
    },
    refund_operator:{
        type:String,
        trim:true
    },
    claim_id:{
        type:Number
    },
    chargeback_id:{
        type:Number
    },
    marketplace:{
        type:String,
        trim:true
    },
    order_id:{
        type:Number
    },
    merchant_order_id:{
        type:Number
    },
    campaign_id:{
        type:Number
    },
    campaign_name:{
        type:String,
        trim:true
    },
    activity_url:{
        type:String,
        trim:true
    },
    id:{
        type:Number
    },
    shipment_status:{
        type:String,
        trim:true
    },
    buyer_address:{
        type:String,
        trim:true
    },
    tracking_number:{
        type:Number
    },
    operator_name:{
        type:String,
        trim:true
    },
    store_id:{
        type:Number
    },
    pos_id:{
        type:Number
    },
    external_id:{
        type:Number
    },
    financing_fee:{
        type:Number
    },
    creador:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Usuario'
    },
    estado:{
        type:String,
        trim:true
    },
    registro:{
        type:Date,
        default:Date.now()
    }
})

module.exports = mongoose.model('UploadMercadopagoReportesCobros',UploadMercadopagoReportesCobrosSchema);