const mongoose = require('mongoose');

// mongoosejs.com/docs/schematypes.html
const UploadSantanderUltimosMovimientosSchema = mongoose.Schema({
    tipoCuenta:{
        type:String,
        required:true,
        trim:true
    },
    numeroCuenta:{
        type:String,
        required:true,
        trim:true
    },
    monedaCuenta:{
        type:String,
        required:true,
        trim:true
    },
    fecha:{
        type:Date,
        required:true
    },
    sucOrigen:{
        type:String,
        required:true,
        trim:true
    },
    descSuc:{
        type:String,
        required:true,
        trim:true
    },
    codOperativo:{
        type:String,
        required:true,
        trim:true
    },
    referencia:{
        type:String,
        required:true,
        unique:true,
        trim:true
    },
    concepto:{
        type:String,
        required:true,
        trim:true
    },
    importe:{
        type:Number,
        required:true
    },
    saldo:{
        type:Number,
        required:true
    },
    linea:{
        type:Number,
        required:true
    },
    numDocumento:{
        type:Number
    },
    nombre:{
        type:String,
        trim:true
    },
    estado:{
        type:String,
        required:true,
        trim:true
    },
    creador:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Usuario'
    },
    registro:{
        type:Date,
        default:Date.now()
    }
})

module.exports = mongoose.model('UploadSantanderUltimosMovimientos',UploadSantanderUltimosMovimientosSchema);